name: 'Lucee Script Runner'
description: 'Run Lucee via the command line'
inputs:
  luceeVersion:
    description: Lucee Version to run
    required: true
  webroot:
    description: cfml webroot
    required: true
  execute:
    description: cfml script to execute
    required: true
  extensions:
    description: any additional extensions to install
    required: true
  extensionDir:
    description: a directory containing any Lucee *.lex extentions to manually install
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        pwd
        echo luceeVersion ${{ inputs.luceeVersion }}
        echo webroot ${{ inputs.webroot }}
        echo execute ${{ inputs.execute }}
        echo extensions ${{ inputs.extensions }}
        echo extensionDir ${{ inputs.extensionDir }}
        ant -buildfile ${{ github.action_path }}/build.xml -DluceeVersion="${{ inputs.luceeVersion }}" -Dwebroot="${{ inputs.webroot }}" -Dexecute="${{ inputs.execute }}" -Dextensions="${{ inputs.extensions }}" -DextensionDir="${{ inputs.extensionDir }}"
      shell: bash
