# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lucee-script-runner-maven-cache

      - name: Cache Lucee files
        uses: actions/cache@v3
        with:
          path: _actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
          restore-keys: |
            lucee-downloads

      - name: Run default
        run: ant

      - name: Run Lucee 6
        run: ant -DluceeVersion="6.0.0.492-SNAPSHOT" -Dexecute="/debug.cfm"

      - name: Run Lucee 6 (using Lucee light, no extensions)
        run: ant -DluceeVersion="light-6.0.0.492-SNAPSHOT" -Dexecute="/debug.cfm"

      - name: Run Lucee 6 (using Lucee zero, no extensions, no admin, no docs)
        run: ant -DluceeVersion="zero-6.0.0.492-SNAPSHOT" -Dexecute="/debug.cfm"
